package entity;
// Generated Nov 6, 2013 9:40:25 PM by Hibernate Tools 3.2.1.GA

import dao.RouteUtil;
import javax.faces.bean.ManagedBean;
import javax.faces.bean.SessionScoped;
import org.hibernate.Session;




/**
 * Route generated by hbm2java
 */
@ManagedBean
@SessionScoped
public class Route  implements java.io.Serializable {


     private Integer routeId;
     private String routeName;

    public Route() {
    }

    public Route(String routeName) {
       this.routeName = routeName;
    }
   
    public Integer getRouteId() {
        return this.routeId;
    }
    
    public void setRouteId(Integer routeId) {
        this.routeId = routeId;
    }
    public String getRouteName() {
        return this.routeName;
    }
    
    public void setRouteName(String routeName) {
        this.routeName = routeName;
    }


 public void insertRoute(){
    Session session=RouteUtil.buildsessionFactory().openSession();
    session.beginTransaction();
        Route r = new Route();
        r.setRouteName(this.getRouteName());        
        session.save(r);
    
    session.getTransaction().commit();
    
    
    }

}


